name: deploy gh-pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      MY_SECRET   : ${{ secrets.CUBE_SECRET_NAME }}
      USER_NAME   : pheihuihui
      USER_EMAIL  : pheihuihui@fake.com
      PUBLISH_DIR : Uncategorized/dist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: npm run build
      run: |
        npm run build
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.CUBE_SECRET_NAME }}
        BRANCH: gh-pages
        FOLDER: dist